# SNS Notifications
SNSNotifications:
  - SNSTopicName: ${Application}-${Environment}-notification-email-topic
    SSMDefaultSubEmail: ${SSMDefaultSubEmail}
    NamePrefix: ${Application}-${Environment}
